### ISSUE TITLE
Getting an error while running for first time with the Token

### ISSUE THREAD

**Issue by nikhilbansal18** [SimonLight001/DNASFirehose_MongoDB_Handler#1]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 87, in <module>
    apiKey = get_API_Key_and_auth()
  File "index.py", line 38, in get_API_Key_and_auth
    decodedJWT = jwt.decode(token, pubKey)
  File "D:\Program Files\Python\lib\site-packages\jwt\api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\jwt\api_jwt.py", line 86, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

**Comment by nikhilbansal18** [comment]
It works with line: 

decodedJWT = jwt.decode(token, pubKey, algorithms=["RS256"], options={"verify_signature": False})
